---

# Install Core components (or remove)?
# One of 'present' or 'absent'.
core_state: present

core_deploy_priority_classes: yes
# If deploying (or un-deploying) priority classes
# do we also include the default?
core_include_default_priority_class: yes

core_deploy_cluster_issuer: yes
core_cluster_issuer_letsencrypt_email: SetMe
